name: ChannelMove
version: '${version}'
main: com.binggre.channelMove.ChannelMove
api-version: '1.20'
authors: [ binggre ]
depend: [ 'BinggreAPI', 'MMOPlayerData', 'MongoLibraryPlugin', 'VelocitySocketClient', 'Citizens' ]
commands:
  채널: